### ISSUE TITLE
Move over gorl functionality to stones/core

### ISSUE THREAD

**Issue by jlund3** [Rauko1753/stones#1]
Eventually, all the code from gorl should live in stones/core. This isn't quite as simple as simply moving it though since the model in these two packages is slightly different. In gorl it is grid based, and in stones it is link based. Consequently, some of this functionality will have to be heavily modified or abandoned.

List of missing functionality:

* AI
  - [x] Pathfinding
  - [x] Fields
* Gen
  - [x] Heightmap
  - [ ] Fence, Fill, Scatter
  - [ ] Cavern
  - [x] Maze, Dungeon
* Model
  - [x] DeltaClock
* Story
  - [x] NameGen
* UI
  - [x] LogWidget
  - [x] CameraWidget, Camera
  - [x] ListSelect
  - [x] Targetting, Marker
* View
  - [x] LoS
  - [x] Trace

**Comment by Rauko1753** [comment]
A few things do not directly port or were in fact missing from gorl so I am calling this one complete!
